spring.application.name=bookstore_mongodb

## mongo db setup
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=bookstore

logging.level.org.springframework.data.mongodb.core=DEBUG

jwt.secret=cpsc449-bookstore-secret-key-must-be-at-least-256-bits-long!
jwt.expiration=84000000